flosse/rust-web-framework-comparison

- README.md
Warning! Self-promotion of a quick and dirty rust web project ;)
You may close this PR. Anyway, I feel like rust ecosystem must live so adding project keep it alive.
> Self-promoting real-world web project

- rocket/Cargo.toml
- rocket/examples/hello_world.rs
Hello, fellows.
I am added example for rocket framework as was asked in issue #20.
> [Feat] add rocket example

- tiny-http/examples/hello_world.rs
it seems that ServerBuilder is no longer used.
> Update tinyhttp server create code

- README.md
- gotham/Cargo.lock
- gotham/Cargo.toml
- gotham/examples/hello_world.rs
Hoping you'll consider this pull request for your examples repository which adds details of the (Gotham web framework for Rust](https://gotham.rs).
Let me know if there are any rough edges!
ps: Appreciate all the effort put into this, a great resource for the community.
> Add the Gotham web framework

- README.md
> actix-web user guide moved

- README.md
https://github.com/trezm/Thruster/commit/5278adb3b147b1a6613348184b8e28f80bbef79f
> Thruster license

- README.md
I've decided to retire the development of Susanoo.
Since Susanoo has not reached a practically usable level at this time, please delete items from the list in order to avoid confusions of the framework users.
> Remove susanoo from server frameworks

- README.md
See: https://github.com/flosse/rust-web-framework-comparison/issues/57
> Iron is not deprecated

- README.md
Fanta has renamed to Thruster.
> Remove fanta

- hyper/examples/hello_world.rs
The example now builds with the latest version of hyper.
> Rewrite the example for hyper

- README.md
> integrate the terra urls for docs and homepage

- README.md
the handlebars readme links to the docs
> add the handlebars documentation url

- README.md
> add squark

- README.md
Hello,
I noticed some links for actix-web were broken, so I tried to look up where they should probably go and fixed them. :)
> fix some broken links for actix-web

- README.md
You can see a rendered version [here](https://github.com/ctjhoa/rust-web-framework-comparison)
#77
> use shields.io for statistics on Low-Level Frameworks

- README.md
Hi @flosse,
I've notice that nickel documentation link in `README.md` is broken
Regards,
> Update nickel documentation link

- README.md
https://github.com/websockets-rs/rust-websocket
> New community repository link to rust-websocket

- README.md
https://github.com/snapview/tokio-tungstenite
> Add tokio-tungstenite

- README.md
I just created this comprehensive demo and thought you may want to add it to your list.
> Add Rocket on Kubernetes demo

- data.toml
> chore: update Tera templating library website URL
